- ros_topic_name: "leo/realsense_d455/camera_info"
  gz_topic_name: "leo/realsense_d455/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo" #
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "leo/realsense_d455/camera_depth"
  gz_topic_name: "leo/realsense_d455/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "leo/realsense_d455/camera_raw"
  gz_topic_name: "leo/realsense_d455/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "leo/realsense_d455/points"
  gz_topic_name: "leo/realsense_d455/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
